### ISSUE TITLE
Register the JSON schemas to schemastore.org

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-jsonschema#54] opened 2023-03-02 12:14 UTC
schemastore.org is one of the largest JSON schema collections. Many IDEs enable us to use JSON schemas served by schemastore.org by default. By serving the JSON schemas of dbt YAML, dbt users don't have to set up custom configurations with the URLs of the schemas on their IDEs. 

https://www.schemastore.org/json/

**Comment by joellabes** [comment] 2023-03-03 00:47
Thanks @yu-iskw! Closing this as a dupe of #3 - we intend to get around to this sometime soon 🤞

**Closed by joellabes** 2023-03-03 00:47 UTC

**Comment by yu-iskw** [comment] 2023-03-03 01:36
@joellabes Sorry for creating a duplicated issue. And thank you for sharing the information. I look forward to the merge.
